exposition:
    resource: "@ExpositionBundle/Controller/"
    type:     annotation
    prefix:   /

museums:
    resource: "@MuseumsBundle/Controller/"
    type:     annotation
    prefix:   /

advertisement:
    resource: "@AdvertisementBundle/Controller/"
    type:     annotation
    prefix:   /advertisements

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /users

index:
    resource: "@IndexBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
   resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_reset:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc