security:
    encoders:
        FOS\UserBundle\Model\UserInterface:
            algorithm:           sha512
            encode_as_base64:    true
            iterations:          5000

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api_doc:
            pattern: ^/api/doc
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:
              path: /logout
              target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/$, role: [ROLE_ADMIN, ROLE_OPERATOR] }
        - { path: ^/advertisements/list, role: ROLE_ADMIN }
        - { path: ^/expositions/, role: ROLE_ADMIN }
        - { path: ^/museums/, role: ROLE_ADMIN }
        - { path: ^/users/, role: ROLE_ADMIN }
        - { path: ^/canton/, role: ROLE_ADMIN }
        - { path: ^/categories/, role: ROLE_ADMIN }
        - { path: ^/criteres/, role: ROLE_ADMIN }
