<?php

namespace UserBundle\Repository;

/**
 * HistoryEntryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoryEntryRepository extends \Doctrine\ORM\EntityRepository
{
}
