services:
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  app.redirect_after_registration_subscriber:
      class: UserBundle\EventListener\RedirectAfterRegistrationSubscriber
      autowire: true
      tags:
        - { name: kernel.event_subscriber }
