<?php

namespace MuseumsBundle\Repository;

/**
 * MuseumImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuseumImageRepository extends \Doctrine\ORM\EntityRepository
{
}
