<?php

namespace ExpositionBundle\Repository;

/**
 * ExpositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionRepository extends \Doctrine\ORM\EntityRepository
{
    public function search($data, $page = 0, $max = NULL, $getResult = true)
    {
        $qb = $this->_em->createQueryBuilder();
        $query = isset($data['query']) && $data['query']?$data['query']:null;

        $qb
            ->select('e')
            ->from('ExpositionBundle:Exposition', 'e')
        ;

        if ($query) {
            $qb
                ->andWhere('e.name like :query')
                ->setParameter('query', "%".$query."%")
            ;
        }

        if ($max) {
            $preparedQuery = $qb->getQuery()
                ->setMaxResults($max)
                ->setFirstResult($page * $max)
            ;
        } else {
            $preparedQuery = $qb->getQuery();
        }

        return $getResult?$preparedQuery->getResult():$preparedQuery;
    }

    function count_expositions(){
        $qb = $this->_em->createQueryBuilder();
        $qb->select('count(exposition.id)');
        $qb->from('ExpositionBundle:Exposition','exposition');

        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;
    }

    function APIfind($filters){

        $qb = $this->_em->createQueryBuilder();
        $qb
            ->select('e')
            ->from('ExpositionBundle:Exposition', 'e')
        ;

        if (!empty($filters))
        {
            foreach ($filters[0] as $key => $value)
            {
                if($key == '_format'){continue;}

                elseif ($key == 'date')
                {
                    $qb->leftJoin('MuseumsBundle:History\Exposition_History', 'c_h', 'WITH', 'c_h.exposition_id = c.id')
                        ->andWhere('c_h.date = :date')
                        ->setParameter('date', $value);
                }

                if($key == 'after_date')
                {
                    $qb->andWhere('e.start > :value')
                        ->setParameter('value', $value);
                }

                elseif ($key == 'before_date')
                {
                    $qb->andWhere('e.finish > :value')
                        ->setParameter('value', $value);
                }

                elseif($key == 'hosting_museum_name')
                {
                    $qb
                        ->innerJoin('e.hosting_museum', 'hm', "WITH", "hm.name = :museum")
                        ->setParameter("museum", $value)
                    ;
                }

                elseif ($key == 'offset')
                {
                    $qb->setFirstResult($value-1);
                }

                elseif ($key == 'limit')
                {
                    $qb->setMaxResults($value);
                }

                else{
                    $qb->andWhere('m.'.$key.' = :value')
                        ->setParameter('value', $value);
                }
            }
        }

        /*var_dump($qb->getQuery()->getSQL());
        die('test');*/

        return $qb
            ->getQuery()
            ->getResult();
    }

}
