<?php

namespace ExpositionBundle\Repository;

/**
 * ExpositionImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpositionImageRepository extends \Doctrine\ORM\EntityRepository
{
}
