<?php

namespace MuseumsBundle\Repository\History;

/**
 * Exposition_HistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exposition_HistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
